.gitignore
README.md
src/pci-gateway/README.md
src/pci-gateway/pom.xml
src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/Keys.java
src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/PciGatewayApplication.java
src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/api/RedirectController.java
src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/config/AppProperties.java
src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/config/GatewayClientProperty.java
src/pci-gateway/src/main/resources/application.yml
src/pom.xml

initial code upload

---

src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/api/RedirectController.java

changing substring to only use the first part of the query

only take the first part of the query string

---

src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/api/RedirectController.java
src/pci-gateway/src/test/java/ca/bc/gov/open/jag/pcigateway/api/RedirectControllerTest.java

Adding unit test for the redirect controller

Adding first test for controller

---

src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/Keys.java
src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/api/RedirectController.java
src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/utils/QueryStringUtils.java

Moving merchantId out

---

.github/dependabot.yml
.github/pull_request_template.md
.github/workflows/code-climate-test-coverage.yaml
README.md
src/pci-gateway/pom.xml

- Adding NTT Default repo configuration

Adding default github config

---

src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/Keys.java
src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/api/RedirectController.java
src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/config/GatewayConfig.java
src/pci-gateway/src/test/java/ca/bc/gov/open/jag/pcigateway/api/RedirectControllerTest.java

- Changing behavior of the transaction endpoint to execute the request

Adding executing http call

---

src/pci-gateway/pom.xml
src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/config/GatewayConfig.java

- {List all the changes, if possible add the jira ticket #}

adding gateway configuration

---

src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/PciGatewayApplication.java

Enable all certificates for testing

enable all certificates

---

src/pci-gateway/pom.xml

remove apache

---

src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/api/RedirectController.java
src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/utils/HttpServletRequestUtils.java

- simplifying getting the merchant_id

moving logic to utils

---

.github/workflows/code-climate-test-coverage.yaml

fixing code ceverage

---

README.md

document encryption

---

src/pci-gateway/src/main/resources/logback-spring.xml

- {List all the changes, if possible add the jira ticket #}

add configuration

---

README.md
src/pci-gateway/pom.xml
src/pci-gateway/src/main/resources/application.yml
src/pci-gateway/src/main/resources/logback-spring.xml

- Adding splunk logging configuration for logback

Splunk logging

---

.github/workflows/integration-tests.yaml

Renaming integration tests

---

src/pci-gateway-test-runner/pom.xml
src/pci-gateway/pom.xml
src/pom.xml

Update version 0.0.2

---

README.md

- Adding integration tests badge to the repo 🦡 

🦡 🦡 you earned a badge 🦡 🦡 

---

src/pci-gateway/src/main/java/ca/bc/gov/open/jag/pcigateway/api/RestProxyController.java

Set content type for bambora requests

Set posts content type

---

src/pci-gateway-test-runner/pom.xml
src/pci-gateway/pom.xml
src/pom.xml

- {List all the changes, if possible add the jira ticket #}

Fix for log4j (again)

---

src/pci-gateway-test-runner/pom.xml
src/pci-gateway/pom.xml
src/pom.xml

Updates the log4j libs to 2.17.1

log4j update
